### ISSUE TITLE
The PR #23 is not in the 0.3.0 build 

### ISSUE THREAD

**Issue by woss** [marcj/typedoc-plugin-lerna-packages#27]
Hi guys, the fix you made here https://github.com/marcj/typedoc-plugin-lerna-packages/pull/23#issue-441353374 is not in the latest build `0.3.0` for all others who cannot wait for this issue to be published use this package https://www.npmjs.com/package/woss-typedoc-plugin-lerna-packages it is the SAME as this master but has the fix in the build

please when you guys make a build and publish it, let me know and i will remove the package 🙌

**Comment by marcj** [comment]
fix released in 0.3.1
